sourcecode:
  view: "https://github.com/CoderDojoPotsdam/regex-tutorial/tree/master"
  edit: "https://github.com/CoderDojoPotsdam/regex-tutorial/edit/master"
  pullrequest: "https://github.com/CoderDojoPotsdam/regex-tutorial/compare"
  newissue: "https://github.com/CoderDojoPotsdam/regex-tutorial/issues/new"
